import { ColorStylesStrict } from '../wxtools';

export const __colorStyles_default_preset: ColorStylesStrict = {
	base: {
		parent: undefined,
		name: 'base',
		fill: 'gradient',
		isolineColor: 'inverted',
		isolineText: true,
		vectorType: 'arrows',
		vectorColor: 'inverted',
		streamLineColor: '#777',
		streamLineSpeedFactor: 1,
		streamLineStatic: false,
		showBelowMin: true,
		showAboveMax: true,
		colorScheme: 'rainbow',
		colors: undefined,
		colorMap: undefined,
		levels: undefined,
		blurRadius: 0,
		addDegrees: 0,
		units: '',
		extraUnits: undefined,
	},
	custom: {
		parent: undefined,
		name: 'custom',
		fill: 'gradient',
		isolineColor: 'inverted',
		isolineText: true,
		vectorType: 'arrows',
		vectorColor: 'inverted',
		streamLineColor: '#777',
		streamLineSpeedFactor: 1,
		streamLineStatic: false,
		showBelowMin: true,
		showAboveMax: true,
		colorScheme: 'rainbow',
		colors: undefined,
		colorMap: undefined,
		levels: undefined,
		blurRadius: 0,
		addDegrees: 0,
		units: '',
		extraUnits: undefined,
	},
};
